# Generated by Django 2.1.5 on 2019-04-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='userpass',
            field=models.CharField(max_length=50),
        ),
    ]
