# Generated by Django 2.1.5 on 2019-04-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190430_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userlogin',
            new_name='login',
        ),
    ]
