# Generated by Django 2.1.5 on 2019-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190501_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactalname', models.CharField(max_length=50)),
                ('contactemail', models.EmailField(max_length=254)),
                ('contactsubject', models.CharField(max_length=50)),
                ('contactmassage', models.CharField(max_length=50)),
            ],
        ),
    ]
