# Generated by Django 2.1.5 on 2019-05-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hospitaldata2_hospitalemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldata2',
            name='hospitalemail',
        ),
    ]
