# Generated by Django 2.1.5 on 2019-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_hospitaldata2_hospitalemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldata2',
            name='hospitalemail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='hospitaldata2',
            name='hospitalpassword',
            field=models.CharField(default='', max_length=20),
        ),
    ]
