# Generated by Django 2.1.5 on 2019-06-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190627_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldata2',
            name='hospitalname',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='app.hospitaldata'),
        ),
    ]
