# Generated by Django 2.1.5 on 2019-06-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_hospitaldata2_hospitalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldata2',
            name='hospitalname',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.hospitaldata'),
        ),
    ]
