# Generated by Django 2.1.5 on 2019-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_hospitaldata2_hospitalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldata2',
            name='deptdescription',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='hospitaldata2',
            name='deptname',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
